title: "Sportify Analytics"
description: "Opinions that you didn't know you didn't need to hear"
permalink: /:title/
theme-color: "#2F4454"
gravatar: eaa3cc978770998ea2bd4382935bf0f4
sponsor_inquiry: https://github.com/sponsors/elementary?frequency=one-time
analytics: https://plausible.io/blog.elementary.io

facebook: elementaryos
mastodon: elementary
reddit: elementaryos
twitter: elementary

authors:
  tristan:
    name: "Tristan Ro"
    description: "Founder & Head of NFL"
  amanjit:
    name: "Amanjit Dhadwar"
    description: "Product Manager & Head of Footy"
    #gravatar: 41275ecc8271aca852ce2c0ff72d2610 # Gravatar md5 hash
  john:
    name: "John Costello"
    description: "Editor & Head of NBA"
    #gravatar: 1f3cc76b99b5d0dae8381a23f52ea96d
  cole:
    name: "Cole Moorcroft"
    description: "Head of NHL"
    #gravatar: 80b17b7bacb372004600451a7eb40b35
  scott:
    name: "Scott Gray"
    description: "Content Creator"
    #gravatar: 2623034032315d5cf0bcf5e213ff5547
  nick:
    name: "Nick Stratford"
    description: "Copywriter & Content Creator"
    # gravatar: e0ac5d5e717da67a36ac72adf235bc42
  nfl:
    name: "NFL Team"
    description: "Amanjit, Cole, John, Scott, Tristan"
  anonymous:
    name: "Unknown Author"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
